/* eslint-disable */
/* This file is generated by protoc-gen-ts-msw-handlers */
/* Do not edit this file manually */
import { http, HttpResponse } from 'msw'
const ApiV1AuthDiscordCallbackGetHandler = http.get('/api/v1/auth/discord/callback',() => {
  return HttpResponse.json({
    value:'',
  })
})
const ApiV1AuthTokenPostHandler = http.post('/api/v1/auth/token',() => {
  return HttpResponse.json({
    expired_at:'',
    refresh_token:'mzxm}e~}}ua',
    access_token:'mzxm}e~}}ua',
  })
})
const ApiV1AuthDiscordGetHandler = http.get('/api/v1/auth/discord',() => {
  return HttpResponse.json({
    value:'',
  })
})
const ApiV1AuthSignUpPostHandler = http.post('/api/v1/auth/sign_up',() => {
  return HttpResponse.json({
    id:'f5221cab-c35c-4fa0-9b7b-9e4bd1f0d4b8',
    name:'Xander Hessel Jr.',
    display_name:'Xander Hessel Jr.',
    avatar_url:'https://placehold.jp/150x150.png',
    profile:'odio atque quaerat aut fugit odit suscipit et sint nulla optio ab dolores saepe rem aliquid aut id veniam ut temporibus corporis vero sint ea in quidem harum qui excepturi quae aut itaque animi aliquam amet explicabo voluptate deleniti sapiente.',
    twitter_id:'47e7f71c-3f1b-4306-93c3-c7d4265e1d42',
    github_id:'01d65eb7-3089-40a2-8951-832bbc49bbf8',
    created_at:'2021-09-01T00:00:00Z',
    updated_at:'2021-09-01T00:00:00Z',
  })
})
export const authServiceHandlers = [
  ApiV1AuthDiscordCallbackGetHandler,
  ApiV1AuthTokenPostHandler,
  ApiV1AuthDiscordGetHandler,
  ApiV1AuthSignUpPostHandler,
]
