/* eslint-disable */
/* This file is generated by protoc-gen-ts-msw-handlers */
/* Do not edit this file manually */
import { http, HttpResponse } from 'msw'
const ApiV1AuthDiscordCallbackGetHandler = http.get('/api/v1/auth/discord/callback',() => {
  return HttpResponse.json({
    value:'',
  })
})
const ApiV1AuthTokenPostHandler = http.post('/api/v1/auth/token',() => {
  return HttpResponse.json({
    expired_at:'',
    refresh_token:'y{l{hijtqjtzgvxp',
    access_token:'y{l{hijtqjtzgvxp',
  })
})
const ApiV1AuthDiscordGetHandler = http.get('/api/v1/auth/discord',() => {
  return HttpResponse.json({
    value:'',
  })
})
const ApiV1AuthSignUpPostHandler = http.post('/api/v1/auth/sign_up',() => {
  return HttpResponse.json({
    id:'01bad699-054d-45ef-aa8f-86ba01ef5fb4',
    name:'Asa Gulgowski',
    display_name:'Asa Gulgowski',
    avatar_url:'https://www.wed.biz/xrw-pnx',
    profile:'aut sunt dignissimos amet dicta voluptates cupiditate aut numquam dolorem minima numquam culpa iure voluptatibus consequuntur ipsa animi quo dolores eum voluptatum aut repellat voluptas et fugiat adipisci ut ipsam dolores vero molestiae doloribus eos est tempore odio illum est.',
    twitter_id:'103c831d-0c5b-4576-9c0a-c86b334ab11e',
    github_id:'17ff1139-628e-4b85-9c4c-1de9e8c4560f',
    created_at:'2021-09-01T00:00:00Z',
    updated_at:'2021-09-01T00:00:00Z',
  })
})
export const authServiceHandlers = [
  ApiV1AuthDiscordCallbackGetHandler,
  ApiV1AuthTokenPostHandler,
  ApiV1AuthDiscordGetHandler,
  ApiV1AuthSignUpPostHandler,
]
