import type { ReactNode } from 'react';

import { Inter } from 'next/font/google';

import './globals.css';
import { WithHeader } from '@/components/Layout/WithHeader';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }): ReactNode => (
  <html lang="en">
    <body className={`min-h-screen ${inter.className}`}>
      <WithHeader className="h-screen flex flex-col">{children}</WithHeader>
    </body>
  </html>
);

export default RootLayout;
