/* eslint-disable */
/* This file is generated by protoc-gen-ts-msw-handlers */
/* Do not edit this file manually */
import { http, HttpResponse } from 'msw'
const ApiV1AssetsPostHandler = http.post('/api/v1/assets',() => {
  return HttpResponse.json({
    id:'811ffd91-3ef0-41ed-a0f5-ee83d6ae8a3e',
  })
})
const ApiV1AssetsIdDeleteHandler = http.delete('/api/v1/assets/{id}',() => {
  return HttpResponse.json({
    status:'ok',
  })
})
export const assetsServiceHandlers = [
  ApiV1AssetsPostHandler,
  ApiV1AssetsIdDeleteHandler,
]
