/* eslint-disable */
/* This file is generated by protoc-gen-ts-msw-handlers */
/* Do not edit this file manually */
import { http, HttpResponse } from 'msw'
const ApiV1TagsGetHandler = http.get('/api/v1/tags',() => {
  return HttpResponse.json({
    tags:[
    {
    id:'35701d5c-a7ce-4f16-8eb6-397840646007',
    name:'Asa Gulgowski',
    color:'#C44549',
    },
    {
    id:'95c20d45-b46a-427e-a782-15ada4e9056b',
    name:'Asa Gulgowski',
    color:'#C44549',
    },
    ],
  })
})
const ApiV1TagsPostHandler = http.post('/api/v1/tags',() => {
  return HttpResponse.json({
    id:'efae644f-51cf-4b2c-965d-a3f7243a12b5',
    name:'Asa Gulgowski',
    color:'#C44549',
  })
})
const ApiV1TagsTagIdGetHandler = http.get('/api/v1/tags/{tag_id}',() => {
  return HttpResponse.json({
    id:'a8f94ea5-c492-44b8-8370-1acfacad805a',
    name:'Asa Gulgowski',
    color:'#C44549',
  })
})
const ApiV1TagsTagIdPutHandler = http.put('/api/v1/tags/{tag_id}',() => {
  return HttpResponse.json({
    id:'34b9c70c-0c92-4934-899a-617617071798',
    name:'Asa Gulgowski',
    color:'#C44549',
  })
})
const ApiV1TagsTagIdDeleteHandler = http.delete('/api/v1/tags/{tag_id}',() => {
  return HttpResponse.json({
    message:'',
  })
})
export const tagsServiceHandlers = [
  ApiV1TagsGetHandler,
  ApiV1TagsPostHandler,
  ApiV1TagsTagIdGetHandler,
  ApiV1TagsTagIdPutHandler,
  ApiV1TagsTagIdDeleteHandler,
]
