/* eslint-disable */
/* This file is generated by protoc-gen-ts-msw-handlers */
/* Do not edit this file manually */
import { http, HttpResponse } from 'msw'
const ApiV1TagsGetHandler = http.get('/api/v1/tags',() => {
  return HttpResponse.json({
    tags:[
    {
    id:'aae272e1-737a-467e-8eb0-981d21fedbeb',
    name:'Xander Hessel Jr.',
    color:'#343B04',
    },
    {
    id:'a689468e-c291-4e2c-935c-6ce43b14fa32',
    name:'Xander Hessel Jr.',
    color:'#343B04',
    },
    {
    id:'9fcca1f4-f37a-493a-94d2-1ab81a0ba3ab',
    name:'Xander Hessel Jr.',
    color:'#343B04',
    },
    {
    id:'b7aeaeba-42ac-4647-a8ea-23b9b4ac4ce7',
    name:'Xander Hessel Jr.',
    color:'#343B04',
    },
    ],
  })
})
const ApiV1TagsPostHandler = http.post('/api/v1/tags',() => {
  return HttpResponse.json({
    id:'15dcf5ee-480d-4973-bca9-bbf6797ca51c',
    name:'Xander Hessel Jr.',
    color:'#343B04',
  })
})
const ApiV1TagsTagIdGetHandler = http.get('/api/v1/tags/{tag_id}',() => {
  return HttpResponse.json({
    id:'14006ffc-4e04-4519-a0fa-d1ed546f9b4e',
    name:'Xander Hessel Jr.',
    color:'#343B04',
  })
})
const ApiV1TagsTagIdPutHandler = http.put('/api/v1/tags/{tag_id}',() => {
  return HttpResponse.json({
    id:'267706cd-b5f1-45e4-a050-18e4a125cd93',
    name:'Xander Hessel Jr.',
    color:'#343B04',
  })
})
const ApiV1TagsTagIdDeleteHandler = http.delete('/api/v1/tags/{tag_id}',() => {
  return HttpResponse.json({
    message:'',
  })
})
export const tagsServiceHandlers = [
  ApiV1TagsGetHandler,
  ApiV1TagsPostHandler,
  ApiV1TagsTagIdGetHandler,
  ApiV1TagsTagIdPutHandler,
  ApiV1TagsTagIdDeleteHandler,
]
