/* eslint-disable */
/* This file is generated by protoc-gen-ts-msw-handlers */
/* Do not edit this file manually */
import { http, HttpResponse } from 'msw'
const ApiV1TagsGetHandler = http.get('/api/v1/tags',() => {
  return HttpResponse.json({
    tags:[
    {
    id:'c143d2a2-1522-4936-b511-c84f892d6222',
    name:'Mr. Augustus Kihn V',
    color:'#AD0A61',
    },
    {
    id:'8eb89ccc-db27-47d3-b4a6-dafaec94b96d',
    name:'Mr. Augustus Kihn V',
    color:'#AD0A61',
    },
    {
    id:'70cc0f48-fda7-49b2-889d-599cb8f1c4ed',
    name:'Mr. Augustus Kihn V',
    color:'#AD0A61',
    },
    ],
  })
})
const ApiV1TagsPostHandler = http.post('/api/v1/tags',() => {
  return HttpResponse.json({
    id:'f30b55d9-7bcd-494a-baf6-79aa40207924',
    name:'Mr. Augustus Kihn V',
    color:'#AD0A61',
  })
})
const ApiV1TagsTagIdGetHandler = http.get('/api/v1/tags/{tag_id}',() => {
  return HttpResponse.json({
    id:'0063b8fa-d798-47c2-931e-aebcf455009b',
    name:'Mr. Augustus Kihn V',
    color:'#AD0A61',
  })
})
const ApiV1TagsTagIdPutHandler = http.put('/api/v1/tags/{tag_id}',() => {
  return HttpResponse.json({
    id:'4d700716-f3ae-44f5-a326-52b1d85fb5d5',
    name:'Mr. Augustus Kihn V',
    color:'#AD0A61',
  })
})
const ApiV1TagsTagIdDeleteHandler = http.delete('/api/v1/tags/{tag_id}',() => {
  return HttpResponse.json({
    message:'',
  })
})
export const tagsServiceHandlers = [
  ApiV1TagsGetHandler,
  ApiV1TagsPostHandler,
  ApiV1TagsTagIdGetHandler,
  ApiV1TagsTagIdPutHandler,
  ApiV1TagsTagIdDeleteHandler,
]
