import type { ReactNode } from 'react';

import { WithFooter } from '@/components/Layout/WithFooter';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }): ReactNode => (
  <WithFooter>{children}</WithFooter>
);

export default RootLayout;
